version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vyg1xuf1gr1l"
s3_prefix = "todo-sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
